# Generated by Django 5.1.3 on 2024-11-24 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='email',
            field=models.CharField(default='temp@gmail.com', max_length=600, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=600, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
